#!/bin/sh
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                                     #
# Copyright (C) 2017 Matteo Sanfelici <matteosanfelici@gmail.com>                     #
#                                                                                     #
# Permission is hereby granted, free of charge, to any person obtaining a copy of     #
# this software and associated documentation files (the "Software"), to deal in the   #
# Software without restriction, including without limitation the rights to use,       #
# copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the     #
# Software, and to permit persons to whom the Software is furnished to do so, subject #
# to the following conditions:                                                        #
#                                                                                     #
# The above copyright notice and this permission notice shall be included in all      #
# copies or substantial portions of the Software.                                     #
#                                                                                     #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, #
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A       #
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT  #
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION   #
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      #
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                              #
#                                                                                     #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

JTS_HOME=/usr/lib/JolieTestSuite
jolie $JTS_HOME/__clients_generator/generate_clients.ol "$@" ./test_suite/ yes
jolie $JTS_HOME/__metadata_tools/getDependenciesPort.ol "$@"
